### ISSUE TITLE
Checksum error

### ISSUE THREAD

**Issue by SVSwift** [beworker/co2monitor#1]
After manually starting co2monitor with
`user@host:/home/user/co2monitor# python ./sensor/monitor.py /dev/hidraw0`
I get the following errors:
```
('52 29 24 9F 0D 00 00 00', ' => ', 'B8 D2 1C 7C 46 91 E8 2B', 'Checksum error')
('41 00 00 41 0D 00 00 00', ' => ', '74 52 1A 5C 41 71 E8 44', 'Checksum error')
('43 0A 3D 8A 0D 00 00 00', ' => ', '1B F2 1A 9C 42 B1 E8 2D', 'Checksum error')
('42 12 3C 90 0D 00 00 00', ' => ', '5B D2 1A 7C 43 B1 E8 2A', 'Checksum error')
```
How can I trace that

**Comment by sergejsha** [comment]
The `monitor.py` script used in this project was originally published in https://hackaday.io/project/5301-reverse-engineering-a-low-cost-usb-co-monitor/log/17909-all-your-base-are-belong-to-us

I would suggest to go though other forks of this script to find the answer. Like this one, for example:
https://github.com/heinemml/CO2Meter/issues?q=checksum

Since I haven't had this issue with my installation I couldn't really help.
